/**
 * Seed data for AgentMatch — 8 sample agents and 5 sample sellers,
 * all in the Austin, TX metro so service areas overlap realistically.
 *
 * Used by the in-memory mock database (src/lib/mock-db.ts) and mirrored
 * in supabase/seed.sql for real Supabase deployments.
 */

import { Agent, Seller } from "./types";
import { calculateIntentScore } from "./matching";

const daysAgo = (n: number) =>
  new Date(Date.now() - n * 24 * 60 * 60 * 1000).toISOString();

export const SEED_AGENTS: Agent[] = [
  {
    id: "agent-1",
    full_name: "Maria Vasquez",
    brokerage: "Compass Austin",
    email: "maria.vasquez@example.com",
    phone: "(512) 555-0101",
    license_number: "TX-701442",
    service_zip_codes: ["78701", "78702", "78703", "78704"],
    years_experience: 14,
    total_homes_sold: 412,
    homes_sold_last_12mo: 38,
    avg_days_on_market: 18,
    avg_list_to_sale_ratio: 1.02,
    specialties: ["luxury", "relocation", "first_time_sellers"],
    bio: "Top 1% Austin agent focused on central neighborhoods. Known for record-setting sale prices and white-glove service from listing to close.",
    photo_url: "https://i.pravatar.cc/300?img=47",
    created_at: daysAgo(320),
  },
  {
    id: "agent-2",
    full_name: "Derrick Cole",
    brokerage: "Keller Williams South Austin",
    email: "derrick.cole@example.com",
    phone: "(512) 555-0102",
    license_number: "TX-688210",
    service_zip_codes: ["78745", "78748", "78749", "78739"],
    years_experience: 9,
    total_homes_sold: 205,
    homes_sold_last_12mo: 31,
    avg_days_on_market: 22,
    avg_list_to_sale_ratio: 0.99,
    specialties: ["first_time_sellers", "relocation", "condos"],
    bio: "South Austin specialist helping families relocate in and out of Texas. Fast, communicative, and data-driven on pricing.",
    photo_url: "https://i.pravatar.cc/300?img=12",
    created_at: daysAgo(280),
  },
  {
    id: "agent-3",
    full_name: "Priya Raman",
    brokerage: "Redfin",
    email: "priya.raman@example.com",
    phone: "(512) 555-0103",
    license_number: "TX-712905",
    service_zip_codes: ["78702", "78721", "78723", "78724"],
    years_experience: 6,
    total_homes_sold: 118,
    homes_sold_last_12mo: 26,
    avg_days_on_market: 15,
    avg_list_to_sale_ratio: 1.04,
    specialties: ["fixer", "investor_deals", "multifamily"],
    bio: "East Austin expert with a deep investor network. If your home needs work or you want a fast as-is sale, I can bring multiple offers in days.",
    photo_url: "https://i.pravatar.cc/300?img=32",
    created_at: daysAgo(240),
  },
  {
    id: "agent-4",
    full_name: "Tom Whitaker",
    brokerage: "Whitaker & Associates",
    email: "tom.whitaker@example.com",
    phone: "(512) 555-0104",
    license_number: "TX-590331",
    service_zip_codes: ["78731", "78759", "78750", "78726"],
    years_experience: 22,
    total_homes_sold: 640,
    homes_sold_last_12mo: 17,
    avg_days_on_market: 28,
    avg_list_to_sale_ratio: 0.98,
    specialties: ["probate", "senior_downsizing", "luxury"],
    bio: "Two decades guiding Northwest Hills families through estate sales, probate, and downsizing with patience and discretion.",
    photo_url: "https://i.pravatar.cc/300?img=59",
    created_at: daysAgo(400),
  },
  {
    id: "agent-5",
    full_name: "Jasmine Okafor",
    brokerage: "Opendoor Brokerage",
    email: "jasmine.okafor@example.com",
    phone: "(512) 555-0105",
    license_number: "TX-734118",
    service_zip_codes: ["78744", "78745", "78741", "78748"],
    years_experience: 5,
    total_homes_sold: 96,
    homes_sold_last_12mo: 29,
    avg_days_on_market: 12,
    avg_list_to_sale_ratio: 0.97,
    specialties: ["investor_deals", "fixer", "divorce"],
    bio: "Speed and certainty are my specialty. I help sellers who need a clean, fast exit — cash buyers, flexible closings, zero drama.",
    photo_url: "https://i.pravatar.cc/300?img=25",
    created_at: daysAgo(190),
  },
  {
    id: "agent-6",
    full_name: "Alan Kim",
    brokerage: "eXp Realty",
    email: "alan.kim@example.com",
    phone: "(512) 555-0106",
    license_number: "TX-699004",
    service_zip_codes: ["78701", "78704", "78741", "78751"],
    years_experience: 8,
    total_homes_sold: 175,
    homes_sold_last_12mo: 24,
    avg_days_on_market: 20,
    avg_list_to_sale_ratio: 1.0,
    specialties: ["condos", "first_time_sellers", "relocation"],
    bio: "Downtown condo and townhouse specialist. I've sold in nearly every building in the urban core and know exactly what your unit is worth.",
    photo_url: "https://i.pravatar.cc/300?img=68",
    created_at: daysAgo(150),
  },
  {
    id: "agent-7",
    full_name: "Rebecca Stone",
    brokerage: "Sotheby's International Realty",
    email: "rebecca.stone@example.com",
    phone: "(512) 555-0107",
    license_number: "TX-655772",
    service_zip_codes: ["78703", "78731", "78746", "78733"],
    years_experience: 17,
    total_homes_sold: 380,
    homes_sold_last_12mo: 14,
    avg_days_on_market: 34,
    avg_list_to_sale_ratio: 1.05,
    specialties: ["luxury", "divorce", "relocation"],
    bio: "Luxury and off-market sales west of MoPac. My listings average 105% of asking through curated marketing and qualified-buyer networks.",
    photo_url: "https://i.pravatar.cc/300?img=45",
    created_at: daysAgo(360),
  },
  {
    id: "agent-8",
    full_name: "Marcus Bell",
    brokerage: "Bell Property Group",
    email: "marcus.bell@example.com",
    phone: "(512) 555-0108",
    license_number: "TX-720556",
    service_zip_codes: ["78721", "78723", "78702", "78744"],
    years_experience: 11,
    total_homes_sold: 230,
    homes_sold_last_12mo: 21,
    avg_days_on_market: 25,
    avg_list_to_sale_ratio: 0.96,
    specialties: ["multifamily", "investor_deals", "probate"],
    bio: "Multifamily and small-portfolio specialist. I help landlords and heirs turn rental property into capital, tenant-in-place or vacant.",
    photo_url: "https://i.pravatar.cc/300?img=14",
    created_at: daysAgo(120),
  },
];

const sellerBase: Omit<Seller, "intent_score">[] = [
  {
    id: "seller-1",
    full_name: "Karen Mitchell",
    email: "karen.mitchell@example.com",
    phone: "(512) 555-0201",
    property_address: "2204 Alta Vista Ave",
    city: "Austin",
    state: "TX",
    zip_code: "78704",
    property_type: "single_family",
    condition: "turnkey",
    bedrooms: 4,
    bathrooms: 3,
    square_footage: 2650,
    estimated_value: 1150000,
    timeline: "30_days",
    selling_reason: "relocating",
    selling_goal: "highest_price",
    notes: "Job transfer to Seattle. Recently remodeled kitchen and primary bath.",
    created_at: daysAgo(6),
  },
  {
    id: "seller-2",
    full_name: "Luis Herrera",
    email: "luis.herrera@example.com",
    phone: "(512) 555-0202",
    property_address: "5119 Pinon Trail",
    city: "Austin",
    state: "TX",
    zip_code: "78745",
    property_type: "single_family",
    condition: "fixer",
    bedrooms: 3,
    bathrooms: 2,
    square_footage: 1420,
    estimated_value: 385000,
    timeline: "now",
    selling_reason: "financial_pressure",
    selling_goal: "as_is_sale",
    notes: "Foundation needs work, roof is 20 years old. Want a fast, as-is close.",
    created_at: daysAgo(4),
  },
  {
    id: "seller-3",
    full_name: "Grace Nakamura",
    email: "grace.nakamura@example.com",
    phone: "(512) 555-0203",
    property_address: "801 W 5th St Unit 1204",
    city: "Austin",
    state: "TX",
    zip_code: "78701",
    property_type: "condo",
    condition: "light_updates",
    bedrooms: 2,
    bathrooms: 2,
    square_footage: 1180,
    estimated_value: 720000,
    timeline: "60_days",
    selling_reason: "downsizing",
    selling_goal: "highest_price",
    notes: "Downtown high-rise with lake views. Flexible on closing date.",
    created_at: daysAgo(3),
  },
  {
    id: "seller-4",
    full_name: "Robert Ellison",
    email: "robert.ellison@example.com",
    phone: "(512) 555-0204",
    property_address: "1608 E 12th St",
    city: "Austin",
    state: "TX",
    zip_code: "78702",
    property_type: "multifamily",
    condition: "dated",
    bedrooms: 6,
    bathrooms: 4,
    square_footage: 3200,
    estimated_value: 980000,
    timeline: "90_plus_days",
    selling_reason: "rental_property",
    selling_goal: "investor_offer",
    notes: "Fourplex, fully leased through spring. Prefer to sell tenant-in-place.",
    created_at: daysAgo(2),
  },
  {
    id: "seller-5",
    full_name: "Diane Foster",
    email: "diane.foster@example.com",
    phone: "(512) 555-0205",
    property_address: "7402 Valburn Dr",
    city: "Austin",
    state: "TX",
    zip_code: "78731",
    property_type: "single_family",
    condition: "dated",
    bedrooms: 5,
    bathrooms: 4,
    square_footage: 3900,
    estimated_value: 1650000,
    timeline: "just_exploring",
    selling_reason: "inherited_property",
    selling_goal: "unsure",
    notes: "Inherited my parents' home. Not sure whether to update it first or sell as-is.",
    created_at: daysAgo(1),
  },
];

export const SEED_SELLERS: Seller[] = sellerBase.map((s) => ({
  ...s,
  intent_score: calculateIntentScore(s),
}));
