-- ============================================================
-- AgentMatch — seed data
--
-- Run AFTER supabase/schema.sql.
-- 8 sample agents, 5 sample sellers (Austin, TX metro), and
-- sample matches whose scores/reasons were generated by the real
-- matching algorithm in src/lib/matching.ts.
-- ============================================================

-- ---------------------------- agents ----------------------------
insert into public.agents
  (id, full_name, brokerage, email, phone, license_number, service_zip_codes,
   years_experience, total_homes_sold, homes_sold_last_12mo, avg_days_on_market,
   avg_list_to_sale_ratio, specialties, bio, photo_url)
values
  ('aaaaaaaa-0000-4000-8000-000000000001', 'Maria Vasquez', 'Compass Austin',
   'maria.vasquez@example.com', '(512) 555-0101', 'TX-701442',
   array['78701','78702','78703','78704'], 14, 412, 38, 18, 1.020,
   array['luxury','relocation','first_time_sellers'],
   'Top 1% Austin agent focused on central neighborhoods. Known for record-setting sale prices and white-glove service from listing to close.',
   'https://i.pravatar.cc/300?img=47'),
  ('aaaaaaaa-0000-4000-8000-000000000002', 'Derrick Cole', 'Keller Williams South Austin',
   'derrick.cole@example.com', '(512) 555-0102', 'TX-688210',
   array['78745','78748','78749','78739'], 9, 205, 31, 22, 0.990,
   array['first_time_sellers','relocation','condos'],
   'South Austin specialist helping families relocate in and out of Texas. Fast, communicative, and data-driven on pricing.',
   'https://i.pravatar.cc/300?img=12'),
  ('aaaaaaaa-0000-4000-8000-000000000003', 'Priya Raman', 'Redfin',
   'priya.raman@example.com', '(512) 555-0103', 'TX-712905',
   array['78702','78721','78723','78724'], 6, 118, 26, 15, 1.040,
   array['fixer','investor_deals','multifamily'],
   'East Austin expert with a deep investor network. If your home needs work or you want a fast as-is sale, I can bring multiple offers in days.',
   'https://i.pravatar.cc/300?img=32'),
  ('aaaaaaaa-0000-4000-8000-000000000004', 'Tom Whitaker', 'Whitaker & Associates',
   'tom.whitaker@example.com', '(512) 555-0104', 'TX-590331',
   array['78731','78759','78750','78726'], 22, 640, 17, 28, 0.980,
   array['probate','senior_downsizing','luxury'],
   'Two decades guiding Northwest Hills families through estate sales, probate, and downsizing with patience and discretion.',
   'https://i.pravatar.cc/300?img=59'),
  ('aaaaaaaa-0000-4000-8000-000000000005', 'Jasmine Okafor', 'Opendoor Brokerage',
   'jasmine.okafor@example.com', '(512) 555-0105', 'TX-734118',
   array['78744','78745','78741','78748'], 5, 96, 29, 12, 0.970,
   array['investor_deals','fixer','divorce'],
   'Speed and certainty are my specialty. I help sellers who need a clean, fast exit — cash buyers, flexible closings, zero drama.',
   'https://i.pravatar.cc/300?img=25'),
  ('aaaaaaaa-0000-4000-8000-000000000006', 'Alan Kim', 'eXp Realty',
   'alan.kim@example.com', '(512) 555-0106', 'TX-699004',
   array['78701','78704','78741','78751'], 8, 175, 24, 20, 1.000,
   array['condos','first_time_sellers','relocation'],
   'Downtown condo and townhouse specialist. I''ve sold in nearly every building in the urban core and know exactly what your unit is worth.',
   'https://i.pravatar.cc/300?img=68'),
  ('aaaaaaaa-0000-4000-8000-000000000007', 'Rebecca Stone', 'Sotheby''s International Realty',
   'rebecca.stone@example.com', '(512) 555-0107', 'TX-655772',
   array['78703','78731','78746','78733'], 17, 380, 14, 34, 1.050,
   array['luxury','divorce','relocation'],
   'Luxury and off-market sales west of MoPac. My listings average 105% of asking through curated marketing and qualified-buyer networks.',
   'https://i.pravatar.cc/300?img=45'),
  ('aaaaaaaa-0000-4000-8000-000000000008', 'Marcus Bell', 'Bell Property Group',
   'marcus.bell@example.com', '(512) 555-0108', 'TX-720556',
   array['78721','78723','78702','78744'], 11, 230, 21, 25, 0.960,
   array['multifamily','investor_deals','probate'],
   'Multifamily and small-portfolio specialist. I help landlords and heirs turn rental property into capital, tenant-in-place or vacant.',
   'https://i.pravatar.cc/300?img=14');

-- ---------------------------- sellers ----------------------------
insert into public.sellers
  (id, full_name, email, phone, property_address, city, state, zip_code,
   property_type, condition, bedrooms, bathrooms, square_footage,
   estimated_value, timeline, selling_reason, selling_goal, notes, intent_score)
values
  ('bbbbbbbb-0000-4000-8000-000000000001', 'Karen Mitchell',
   'karen.mitchell@example.com', '(512) 555-0201', '2204 Alta Vista Ave',
   'Austin', 'TX', '78704', 'single_family', 'turnkey', 4, 3, 2650, 1150000,
   '30_days', 'relocating', 'highest_price',
   'Job transfer to Seattle. Recently remodeled kitchen and primary bath.', 91),
  ('bbbbbbbb-0000-4000-8000-000000000002', 'Luis Herrera',
   'luis.herrera@example.com', '(512) 555-0202', '5119 Pinon Trail',
   'Austin', 'TX', '78745', 'single_family', 'fixer', 3, 2, 1420, 385000,
   'now', 'financial_pressure', 'as_is_sale',
   'Foundation needs work, roof is 20 years old. Want a fast, as-is close.', 100),
  ('bbbbbbbb-0000-4000-8000-000000000003', 'Grace Nakamura',
   'grace.nakamura@example.com', '(512) 555-0203', '801 W 5th St Unit 1204',
   'Austin', 'TX', '78701', 'condo', 'light_updates', 2, 2, 1180, 720000,
   '60_days', 'downsizing', 'highest_price',
   'Downtown high-rise with lake views. Flexible on closing date.', 66),
  ('bbbbbbbb-0000-4000-8000-000000000004', 'Robert Ellison',
   'robert.ellison@example.com', '(512) 555-0204', '1608 E 12th St',
   'Austin', 'TX', '78702', 'multifamily', 'dated', 6, 4, 3200, 980000,
   '90_plus_days', 'rental_property', 'investor_offer',
   'Fourplex, fully leased through spring. Prefer to sell tenant-in-place.', 54),
  ('bbbbbbbb-0000-4000-8000-000000000005', 'Diane Foster',
   'diane.foster@example.com', '(512) 555-0205', '7402 Valburn Dr',
   'Austin', 'TX', '78731', 'single_family', 'dated', 5, 4, 3900, 1650000,
   'just_exploring', 'inherited_property', 'unsure',
   'Inherited my parents'' home. Not sure whether to update it first or sell as-is.', 42);

-- ---------------------------- matches ----------------------------
-- Scores and reasons generated by src/lib/matching.ts against the data above.
insert into public.matches (seller_id, agent_id, score, reasons) values
  ('bbbbbbbb-0000-4000-8000-000000000001', 'aaaaaaaa-0000-4000-8000-000000000001', 97,
   array['Actively serves your ZIP code (78704)','Experienced with single family properties','Specializes in luxury — a fit for your goal','Background in luxury and relocation situations like yours']),
  ('bbbbbbbb-0000-4000-8000-000000000001', 'aaaaaaaa-0000-4000-8000-000000000006', 87,
   array['Actively serves your ZIP code (78704)','Experienced with single family properties','Consistently sells at or above list price','Background in first-time sellers and relocation situations like yours']),
  ('bbbbbbbb-0000-4000-8000-000000000001', 'aaaaaaaa-0000-4000-8000-000000000004', 74,
   array['Works in neighborhoods near 78704','Experienced with single family properties','Specializes in luxury — a fit for your goal','Background in luxury situations like yours']),
  ('bbbbbbbb-0000-4000-8000-000000000001', 'aaaaaaaa-0000-4000-8000-000000000007', 74,
   array['Works in neighborhoods near 78704','Experienced with single family properties','Specializes in luxury — a fit for your goal','Background in luxury and relocation situations like yours']),
  ('bbbbbbbb-0000-4000-8000-000000000001', 'aaaaaaaa-0000-4000-8000-000000000002', 66,
   array['Works in neighborhoods near 78704','Experienced with single family properties','Background in first-time sellers and relocation situations like yours','Averages just 22 days on market — matches your urgent timeline']),

  ('bbbbbbbb-0000-4000-8000-000000000002', 'aaaaaaaa-0000-4000-8000-000000000005', 86,
   array['Actively serves your ZIP code (78745)','Specializes in fixer-uppers, investor deals — a fit for your goal','Background in investor deals and fixer-uppers situations like yours','Averages just 12 days on market — matches your urgent timeline']),
  ('bbbbbbbb-0000-4000-8000-000000000002', 'aaaaaaaa-0000-4000-8000-000000000003', 76,
   array['Works in neighborhoods near 78745','Specializes in fixer-uppers, investor deals — a fit for your goal','Background in fixer-uppers and investor deals situations like yours','Averages just 15 days on market — matches your urgent timeline']),
  ('bbbbbbbb-0000-4000-8000-000000000002', 'aaaaaaaa-0000-4000-8000-000000000002', 69,
   array['Actively serves your ZIP code (78745)','Experienced with single family properties','Averages just 22 days on market — matches your urgent timeline','Closed 31 homes in the last 12 months']),
  ('bbbbbbbb-0000-4000-8000-000000000002', 'aaaaaaaa-0000-4000-8000-000000000008', 69,
   array['Works in neighborhoods near 78745','Specializes in investor deals — a fit for your goal','Background in investor deals situations like yours','Averages just 25 days on market — matches your urgent timeline']),
  ('bbbbbbbb-0000-4000-8000-000000000002', 'aaaaaaaa-0000-4000-8000-000000000001', 62,
   array['Works in neighborhoods near 78745','Experienced with single family properties','Averages just 18 days on market — matches your urgent timeline','Closed 38 homes in the last 12 months']),

  ('bbbbbbbb-0000-4000-8000-000000000003', 'aaaaaaaa-0000-4000-8000-000000000006', 87,
   array['Actively serves your ZIP code (78701)','Experienced with condo properties','Consistently sells at or above list price','Background in first-time sellers and relocation situations like yours']),
  ('bbbbbbbb-0000-4000-8000-000000000003', 'aaaaaaaa-0000-4000-8000-000000000001', 84,
   array['Actively serves your ZIP code (78701)','Specializes in luxury — a fit for your goal','Background in relocation and first-time sellers situations like yours','Closed 38 homes in the last 12 months']),
  ('bbbbbbbb-0000-4000-8000-000000000003', 'aaaaaaaa-0000-4000-8000-000000000002', 66,
   array['Works in neighborhoods near 78701','Experienced with condo properties','Background in first-time sellers and relocation situations like yours','Closed 31 homes in the last 12 months']),
  ('bbbbbbbb-0000-4000-8000-000000000003', 'aaaaaaaa-0000-4000-8000-000000000004', 63,
   array['Works in neighborhoods near 78701','Specializes in luxury — a fit for your goal','Background in senior downsizing situations like yours','22 years of local market experience']),
  ('bbbbbbbb-0000-4000-8000-000000000003', 'aaaaaaaa-0000-4000-8000-000000000007', 63,
   array['Works in neighborhoods near 78701','Specializes in luxury — a fit for your goal','Background in relocation situations like yours','17 years of local market experience']),

  ('bbbbbbbb-0000-4000-8000-000000000004', 'aaaaaaaa-0000-4000-8000-000000000003', 92,
   array['Actively serves your ZIP code (78702)','Experienced with multifamily properties','Specializes in investor deals — a fit for your goal','Background in fixer-uppers and investor deals situations like yours']),
  ('bbbbbbbb-0000-4000-8000-000000000004', 'aaaaaaaa-0000-4000-8000-000000000008', 87,
   array['Actively serves your ZIP code (78702)','Experienced with multifamily properties','Specializes in investor deals — a fit for your goal','Background in multifamily and investor deals situations like yours']),
  ('bbbbbbbb-0000-4000-8000-000000000004', 'aaaaaaaa-0000-4000-8000-000000000005', 77,
   array['Works in neighborhoods near 78702','Experienced with multifamily properties','Specializes in investor deals — a fit for your goal','Background in investor deals and fixer-uppers situations like yours']),
  ('bbbbbbbb-0000-4000-8000-000000000004', 'aaaaaaaa-0000-4000-8000-000000000001', 62,
   array['Actively serves your ZIP code (78702)','Closed 38 homes in the last 12 months','14 years of local market experience','Sells at 102% of list price on average']),
  ('bbbbbbbb-0000-4000-8000-000000000004', 'aaaaaaaa-0000-4000-8000-000000000002', 44,
   array['Works in neighborhoods near 78702','Closed 31 homes in the last 12 months']),

  ('bbbbbbbb-0000-4000-8000-000000000005', 'aaaaaaaa-0000-4000-8000-000000000004', 76,
   array['Actively serves your ZIP code (78731)','Experienced with single family properties','Background in probate situations like yours','22 years of local market experience']),
  ('bbbbbbbb-0000-4000-8000-000000000005', 'aaaaaaaa-0000-4000-8000-000000000001', 73,
   array['Works in neighborhoods near 78731','Experienced with single family properties','Specializes in first-time sellers — a fit for your goal','Closed 38 homes in the last 12 months']),
  ('bbbbbbbb-0000-4000-8000-000000000005', 'aaaaaaaa-0000-4000-8000-000000000002', 68,
   array['Works in neighborhoods near 78731','Experienced with single family properties','Specializes in first-time sellers — a fit for your goal','Closed 31 homes in the last 12 months']),
  ('bbbbbbbb-0000-4000-8000-000000000005', 'aaaaaaaa-0000-4000-8000-000000000006', 67,
   array['Works in neighborhoods near 78731','Experienced with single family properties','Specializes in first-time sellers — a fit for your goal','Closed 24 homes in the last 12 months']),
  ('bbbbbbbb-0000-4000-8000-000000000005', 'aaaaaaaa-0000-4000-8000-000000000007', 67,
   array['Actively serves your ZIP code (78731)','Experienced with single family properties','17 years of local market experience','Sells at 105% of list price on average']);

-- ---------------------------- lead statuses ----------------------------
-- One pipeline row per match, defaulting to 'new'.
insert into public.lead_statuses (match_id, agent_id, seller_id, status)
select id, agent_id, seller_id, 'new' from public.matches;

-- Add some pipeline variety for the demo.
update public.lead_statuses set status = 'contacted'
where seller_id = 'bbbbbbbb-0000-4000-8000-000000000001'
  and agent_id = 'aaaaaaaa-0000-4000-8000-000000000001';
update public.lead_statuses set status = 'appointment_set'
where seller_id = 'bbbbbbbb-0000-4000-8000-000000000002'
  and agent_id = 'aaaaaaaa-0000-4000-8000-000000000005';
update public.lead_statuses set status = 'contacted'
where seller_id = 'bbbbbbbb-0000-4000-8000-000000000004'
  and agent_id = 'aaaaaaaa-0000-4000-8000-000000000003';
