/**
 * KAIRO — the last celestial warrior of Planet Veyra.
 *
 * Combat identity: fast, aggressive, mobile, adaptable. Strong aerial pursuit,
 * close-range combo pressure, energy manipulation.
 *
 * Numerically Kairo is defined by:
 *   - the fastest startup in the game (5f jab) and a 4-link ground chain
 *   - the highest mobility ceiling: fastest flight, most air dashes, cheapest
 *     pursuit dash
 *   - the lowest health pool and no innate super armor — he must not get hit
 *
 * Everything below is data. No shared system knows Kairo exists.
 */

import { makeAttack, AttackKind, ReactionType } from '../gameplay/CombatTypes';
import { makeAbility, AbilityKind, InterruptPolicy } from '../gameplay/Ability';
import type { CharacterData } from './CharacterData';

/** Celestial Force palette: deep violet core with a gold celestial edge. */
const VIOLET = 0x9d6bff;
const GOLD = 0xf0c46a;

const attacks = {
  // ---- Ground light chain: fast, low commitment, high frequency ----------
  k_light1: makeAttack({
    id: 'k_light1',
    name: 'Celestial Jab',
    kind: AttackKind.Light,
    startup: 5,
    active: 3,
    recovery: 10,
    damage: 30,
    hitstun: 17,
    blockstun: 11,
    hitstop: 4,
    guardDamage: 7,
    chipDamage: 2,
    knockbackForward: 2.2,
    advance: 3.2,
    reaction: ReactionType.Flinch,
    hitbox: { reach: 1.7, radius: 1.05, height: 1.05, arc: Math.PI * 0.42 },
    cancelFrom: 5,
    cancelInto: ['k_light2'],
    energyOnHit: 20,
    shake: 0.14,
    fx: 'hit_light',
    sfx: 'hit_light',
  }),
  k_light2: makeAttack({
    id: 'k_light2',
    name: 'Rising Palm',
    kind: AttackKind.Light,
    startup: 5,
    active: 3,
    recovery: 11,
    damage: 33,
    hitstun: 18,
    blockstun: 11,
    hitstop: 4,
    guardDamage: 8,
    chipDamage: 2,
    knockbackForward: 2.6,
    advance: 3.6,
    reaction: ReactionType.Flinch,
    hitbox: { reach: 1.8, radius: 1.1, height: 1.15, arc: Math.PI * 0.42 },
    cancelFrom: 5,
    cancelInto: ['k_light3'],
    energyOnHit: 21,
    shake: 0.15,
  }),
  k_light3: makeAttack({
    id: 'k_light3',
    name: 'Spiral Kick',
    kind: AttackKind.Light,
    startup: 6,
    active: 3,
    recovery: 13,
    damage: 38,
    hitstun: 20,
    blockstun: 12,
    hitstop: 5,
    guardDamage: 10,
    chipDamage: 3,
    knockbackForward: 3.4,
    advance: 4.2,
    reaction: ReactionType.Knockback,
    hitbox: { reach: 2.0, radius: 1.15, height: 1.1, arc: Math.PI * 0.45 },
    cancelFrom: 6,
    cancelInto: ['k_light4'],
    energyOnHit: 24,
    shake: 0.2,
    fx: 'hit_medium',
    sfx: 'hit_medium',
  }),
  k_light4: makeAttack({
    id: 'k_light4',
    name: 'Horizon Cut',
    kind: AttackKind.Finisher,
    startup: 8,
    active: 4,
    recovery: 21,
    damage: 58,
    hitstun: 26,
    blockstun: 14,
    hitstop: 8,
    guardDamage: 16,
    chipDamage: 5,
    knockbackForward: 11,
    knockbackUp: 3.5,
    advance: 5.0,
    reaction: ReactionType.Blowaway,
    hitbox: { reach: 2.3, radius: 1.3, height: 1.15, arc: Math.PI * 0.5 },
    cancelFrom: 8,
    cancelInto: [],
    energyOnHit: 34,
    shake: 0.42,
    fx: 'hit_heavy',
    sfx: 'hit_heavy',
  }),

  // ---- Heavy: slow, committal, huge reward -------------------------------
  k_heavy: makeAttack({
    id: 'k_heavy',
    name: 'Nova Strike',
    kind: AttackKind.Heavy,
    startup: 12,
    active: 4,
    recovery: 22,
    damage: 78,
    hitstun: 28,
    blockstun: 15,
    hitstop: 9,
    guardDamage: 22,
    chipDamage: 6,
    knockbackForward: 12,
    knockbackUp: 2.5,
    advance: 5.5,
    reaction: ReactionType.Blowaway,
    hitbox: { reach: 2.4, radius: 1.35, height: 1.1, arc: Math.PI * 0.5 },
    cancelFrom: 12,
    cancelInto: [],
    energyOnHit: 40,
    shake: 0.5,
    fx: 'hit_heavy',
    sfx: 'hit_heavy',
  }),
  k_charged: makeAttack({
    id: 'k_charged',
    name: 'Nova Strike (Charged)',
    kind: AttackKind.Heavy,
    startup: 14,
    active: 5,
    recovery: 26,
    damage: 92,
    hitstun: 32,
    blockstun: 17,
    hitstop: 11,
    guardDamage: 30,
    chipDamage: 9,
    knockbackForward: 15,
    knockbackUp: 4,
    advance: 6.5,
    reaction: ReactionType.Blowaway,
    hitbox: { reach: 2.6, radius: 1.5, height: 1.1, arc: Math.PI * 0.55 },
    energyOnHit: 48,
    shake: 0.62,
    fx: 'hit_heavy',
    sfx: 'hit_heavy',
  }),

  // ---- Launcher: the gateway into aerial combat --------------------------
  k_launcher: makeAttack({
    id: 'k_launcher',
    name: 'Skyward Arc',
    kind: AttackKind.Launcher,
    startup: 10,
    active: 4,
    recovery: 20,
    damage: 50,
    hitstun: 34,
    blockstun: 14,
    hitstop: 7,
    guardDamage: 14,
    chipDamage: 4,
    knockbackForward: 1.5,
    knockbackUp: 15.5,
    advance: 2.2,
    reaction: ReactionType.Launch,
    hitbox: { reach: 2.0, radius: 1.3, height: 1.2, arc: Math.PI * 0.5 },
    cancelFrom: 10,
    cancelInto: [],
    energyOnHit: 30,
    shake: 0.34,
    fx: 'hit_launch',
    sfx: 'hit_launch',
  }),

  // ---- Aerial chain ------------------------------------------------------
  k_air1: makeAttack({
    id: 'k_air1',
    name: 'Air Slash',
    kind: AttackKind.AirLight,
    startup: 5,
    active: 3,
    recovery: 11,
    damage: 30,
    hitstun: 18,
    blockstun: 11,
    hitstop: 4,
    guardDamage: 7,
    knockbackForward: 1.8,
    knockbackUp: 1.6,
    advance: 2.6,
    airOk: true,
    groundOk: false,
    reaction: ReactionType.Flinch,
    hitbox: { reach: 1.8, radius: 1.15, height: 0.9, arc: Math.PI * 0.5 },
    cancelFrom: 5,
    cancelInto: ['k_air2'],
    energyOnHit: 20,
    shake: 0.14,
  }),
  k_air2: makeAttack({
    id: 'k_air2',
    name: 'Orbit Kick',
    kind: AttackKind.AirLight,
    startup: 6,
    active: 3,
    recovery: 12,
    damage: 34,
    hitstun: 19,
    blockstun: 11,
    hitstop: 5,
    guardDamage: 9,
    knockbackForward: 2.2,
    knockbackUp: 2.2,
    advance: 3.0,
    airOk: true,
    groundOk: false,
    reaction: ReactionType.Flinch,
    hitbox: { reach: 1.9, radius: 1.2, height: 0.9, arc: Math.PI * 0.5 },
    cancelFrom: 6,
    cancelInto: ['k_air3'],
    energyOnHit: 22,
    shake: 0.16,
  }),
  k_air3: makeAttack({
    id: 'k_air3',
    name: 'Comet Drop',
    kind: AttackKind.AirHeavy,
    startup: 8,
    active: 4,
    recovery: 18,
    damage: 54,
    hitstun: 24,
    blockstun: 13,
    hitstop: 9,
    guardDamage: 15,
    chipDamage: 4,
    knockbackForward: 3,
    knockbackUp: -16,
    advance: 3.4,
    airOk: true,
    groundOk: false,
    reaction: ReactionType.Slam,
    hitbox: { reach: 2.0, radius: 1.3, height: 0.7, arc: Math.PI * 0.55 },
    energyOnHit: 32,
    shake: 0.46,
    fx: 'hit_heavy',
    sfx: 'hit_heavy',
  }),
  k_airheavy: makeAttack({
    id: 'k_airheavy',
    name: 'Meteor Heel',
    kind: AttackKind.AirHeavy,
    startup: 11,
    active: 5,
    recovery: 20,
    damage: 70,
    hitstun: 26,
    blockstun: 14,
    hitstop: 11,
    guardDamage: 20,
    chipDamage: 6,
    knockbackForward: 2,
    knockbackUp: -22,
    advance: 3.0,
    airOk: true,
    groundOk: false,
    reaction: ReactionType.Slam,
    hitbox: { reach: 2.1, radius: 1.4, height: 0.6, arc: Math.PI * 0.6 },
    energyOnHit: 38,
    shake: 0.55,
    fx: 'hit_heavy',
    sfx: 'hit_heavy',
  }),
};

export const KAIRO: CharacterData = {
  id: 'kairo',
  name: 'KAIRO',
  energyName: 'CELESTIAL FORCE',
  tagline: 'The last celestial warrior of Veyra.',

  maxHealth: 1000,
  energyPerBar: 100,
  energyBars: 5,
  energyPassiveRegen: 3.2,
  energyChargeRate: 78,

  ascensionMax: 1000,
  ascensionGainDealt: 0.55,
  ascensionGainTaken: 0.95,
  ascensionDrain: 62,
  ascensionThreshold: 1.0,

  movement: {
    walkSpeed: 7.6,
    sprintSpeed: 13.8,
    groundAccel: 72,
    groundDecel: 112,
    turnRate: 12.5,

    jumpSpeed: 15.4,
    gravity: 34,
    maxFallSpeed: 42,
    airAccel: 34,
    airSpeed: 10.2,

    flySpeed: 16.5,
    flyVerticalSpeed: 12.5,
    flyAccel: 58,
    boostMultiplier: 2.15,
    boostEnergyPerSecond: 16,

    dashDistance: 6.4,
    dashFrames: 9,
    dashIFrames: 4,
    dashCooldown: 12,
    airDashEnergyCost: 18,
    airDashCharges: 2,

    pursuitSpeed: 62,
    pursuitEnergyCost: 25,
    pursuitRange: 46,
  },

  defense: {
    guardMax: 100,
    guardRegenRate: 15,
    guardRegenDelayFrames: 48,
    guardBreakStunFrames: 58,
    guardDamageReduction: 0.88,

    parryWindowFrames: 6,
    parryPunishFrames: 26,
    parryEnergyReward: 42,

    dodgeFrames: 20,
    dodgeIFrames: 9,
    dodgeCooldown: 16,
    dodgeDistance: 5.2,

    comboEscapeCost: 100,
    comboEscapeIFrames: 34,
    comboEscapeMinHits: 3,
  },

  visual: {
    primaryColor: 0x211a2e,
    secondaryColor: GOLD,
    energyColor: VIOLET,
    rimColor: 0xc7a2ff,
    height: 1.82,
    radius: 0.46,
    build: 'agile',
  },

  audio: { pitch: 1.12, timbre: 'bright' },

  attacks,
  lightChain: ['k_light1', 'k_light2', 'k_light3', 'k_light4'],
  airChain: ['k_air1', 'k_air2', 'k_air3'],
  heavyAttack: 'k_heavy',
  chargedHeavyAttack: 'k_charged',
  launcher: 'k_launcher',
  airHeavyAttack: 'k_airheavy',

  abilities: [
    // 1 — Celestial Bolt: cheap, fast, the tool that makes zoning viable.
    makeAbility({
      id: 'celestial_bolt',
      name: 'Celestial Bolt',
      kind: AbilityKind.Projectile,
      slot: 1,
      energyCost: 45,
      cooldown: 22,
      startup: 8,
      active: 2,
      recovery: 14,
      airOk: true,
      groundOk: true,
      interrupt: InterruptPolicy.Cancellable,
      shake: 0.16,
      fx: 'bolt',
      sfx: 'bolt',
      description: 'A fast lance of celestial energy. Cheap, safe, relentless.',
      projectile: {
        count: 1,
        speed: 58,
        range: 70,
        radius: 0.62,
        damage: 52,
        chipDamage: 9,
        guardDamage: 12,
        hitstun: 19,
        blockstun: 12,
        hitstop: 5,
        knockbackForward: 7,
        knockbackUp: 1.2,
        homingStrength: 0.35,
        fx: 'bolt',
        color: VIOLET,
      },
    }),

    // 2 — Nova Rush: the pursuit tool. Closes any gap, converts into a combo.
    makeAbility({
      id: 'nova_rush',
      name: 'Nova Rush',
      kind: AbilityKind.Rush,
      slot: 2,
      energyCost: 85,
      cooldown: 48,
      startup: 9,
      active: 20,
      recovery: 16,
      rushSpeed: 68,
      rushRange: 40,
      airOk: true,
      groundOk: true,
      armor: 1,
      interrupt: InterruptPolicy.Armored,
      shake: 0.36,
      fx: 'rush',
      sfx: 'rush',
      description: 'Collapse the distance in an instant and strike through.',
      strike: {
        id: 'nova_rush_hit',
        name: 'Nova Rush',
        kind: AttackKind.Ability,
        damage: 76,
        hitstun: 26,
        blockstun: 14,
        hitstop: 10,
        guardDamage: 20,
        chipDamage: 7,
        knockbackForward: 8,
        knockbackUp: 4.5,
        reaction: ReactionType.Knockback,
        hitbox: { reach: 1.9, radius: 1.5, height: 1.0, arc: Math.PI },
        energyOnHit: 26,
        shake: 0.44,
        fx: 'hit_heavy',
        sfx: 'hit_heavy',
      },
    }),

    // 3 — Ascension Breaker: the launcher that opens aerial combos.
    makeAbility({
      id: 'ascension_breaker',
      name: 'Ascension Breaker',
      kind: AbilityKind.Strike,
      slot: 3,
      energyCost: 100,
      cooldown: 66,
      startup: 13,
      active: 6,
      recovery: 24,
      airOk: false,
      groundOk: true,
      armor: 1,
      interrupt: InterruptPolicy.Armored,
      shake: 0.5,
      fx: 'breaker',
      sfx: 'breaker',
      description: 'A rising celestial uppercut that hurls the enemy skyward.',
      strike: {
        id: 'ascension_breaker_hit',
        name: 'Ascension Breaker',
        kind: AttackKind.Ability,
        damage: 88,
        hitstun: 40,
        blockstun: 18,
        hitstop: 12,
        guardDamage: 34,
        chipDamage: 11,
        knockbackForward: 2.5,
        knockbackUp: 21,
        reaction: ReactionType.Launch,
        hitbox: { reach: 2.1, radius: 1.6, height: 1.3, arc: Math.PI * 0.7 },
        energyOnHit: 24,
        shake: 0.6,
        fx: 'hit_launch',
        sfx: 'hit_launch',
      },
    }),

    // 4 — Starfall Barrage: aerial-only pressure that punishes juggled targets.
    makeAbility({
      id: 'starfall_barrage',
      name: 'Starfall Barrage',
      kind: AbilityKind.Barrage,
      slot: 4,
      energyCost: 130,
      cooldown: 90,
      startup: 12,
      active: 44,
      recovery: 20,
      airOk: true,
      groundOk: true,
      interrupt: InterruptPolicy.Cancellable,
      shake: 0.3,
      fx: 'starfall',
      sfx: 'starfall',
      description: 'A rain of descending celestial motes. Area denial from above.',
      projectile: {
        count: 9,
        interval: 5,
        speed: 46,
        range: 62,
        radius: 0.55,
        damage: 26,
        chipDamage: 5,
        guardDamage: 7,
        hitstun: 14,
        blockstun: 9,
        hitstop: 3,
        knockbackForward: 3.5,
        knockbackUp: 1.8,
        homingStrength: 0.55,
        splashRadius: 2.4,
        spread: 0.26,
        fx: 'starfall',
        color: 0xbf9cff,
      },
    }),
  ],

  ultimate: makeAbility({
    id: 'final_horizon',
    name: 'Final Horizon',
    kind: AbilityKind.Ultimate,
    slot: 0,
    energyCost: 400,
    cooldown: 240,
    cinematicFrames: 168,
    captureRange: 15,
    airOk: true,
    groundOk: true,
    interrupt: InterruptPolicy.Uninterruptible,
    shake: 1,
    fx: 'final_horizon',
    sfx: 'final_horizon',
    description:
      'Kairo gathers the fragment of the Celestial Core and collapses a horizon of light onto his enemy.',
    projectile: {
      count: 1,
      speed: 40,
      range: 30,
      radius: 1.1,
      damage: 18,
      chipDamage: 3,
      guardDamage: 4,
      hitstun: 8,
      blockstun: 5,
      hitstop: 2,
      knockbackForward: 1,
      knockbackUp: 0.5,
      homingStrength: 0.9,
      fx: 'final_horizon',
      color: GOLD,
    },
    strike: {
      id: 'final_horizon_hit',
      name: 'Final Horizon',
      kind: AttackKind.Ultimate,
      damage: 340,
      hitstun: 60,
      blockstun: 30,
      hitstop: 20,
      guardDamage: 100,
      chipDamage: 60,
      knockbackForward: 24,
      knockbackUp: 12,
      reaction: ReactionType.Blowaway,
      hitbox: { reach: 0, radius: 6, height: 1.2, arc: Math.PI },
      energyOnHit: 0,
      shake: 1,
      fx: 'final_horizon',
      sfx: 'final_horizon',
    },
  }),

  transformation: {
    id: 'celestial_surge',
    name: 'CELESTIAL SURGE',
    frames: 54,
    damageMultiplier: 1.32,
    defenseMultiplier: 0.82,
    speedMultiplier: 1.24,
    attackSpeedMultiplier: 0.86,
    energyRegenMultiplier: 2.4,
    bonusArmor: 0,
    auraColor: 0xffd66b,
    accentColor: 0xfff3d0,
    audioProfile: 'surge',
    cameraFovBoost: 5,
    fx: 'transform_surge',
    sfx: 'transform_surge',
  },
};
