/**
 * LORD VEYRON — the armored warlord who destroyed Planet Veyra.
 *
 * Combat identity: powerful, deliberate, armored, long reach, heavy knockback,
 * area control, punishing counterattacks.
 *
 * Numerically Veyron is the inverse of Kairo in every axis that matters:
 *   - slower startup everywhere (7f jab vs 5f) but far greater reach and damage
 *   - innate super armor on his heavy and specials — he trades hits and wins
 *   - the largest health pool and guard meter, the worst mobility
 *   - his answer to pressure is Rift Counter, not movement
 *
 * Visual identity is deliberately built for readability against Kairo: cold
 * void-teal against Kairo's warm violet-gold, so at a glance the player always
 * knows whose energy is on screen.
 */

import { makeAttack, AttackKind, ReactionType } from '../gameplay/CombatTypes';
import { makeAbility, AbilityKind, InterruptPolicy } from '../gameplay/Ability';
import type { CharacterData } from './CharacterData';

/** Void Dominion palette: cold teal fracture-light over black warplate. */
const VOID_TEAL = 0x35f0c0;
const VOID_BLACK = 0x0d1418;

const attacks = {
  // ---- Ground light chain: only 3 links, slower, but long and punishing ---
  v_light1: makeAttack({
    id: 'v_light1',
    name: 'Warplate Backhand',
    kind: AttackKind.Light,
    startup: 7,
    active: 3,
    recovery: 12,
    damage: 38,
    hitstun: 18,
    blockstun: 12,
    hitstop: 5,
    guardDamage: 11,
    chipDamage: 3,
    knockbackForward: 3.0,
    advance: 2.6,
    reaction: ReactionType.Flinch,
    hitbox: { reach: 2.2, radius: 1.25, height: 1.1, arc: Math.PI * 0.45 },
    cancelFrom: 7,
    cancelInto: ['v_light2'],
    energyOnHit: 22,
    shake: 0.18,
  }),
  v_light2: makeAttack({
    id: 'v_light2',
    name: 'Gauntlet Sweep',
    kind: AttackKind.Light,
    startup: 8,
    active: 3,
    recovery: 14,
    damage: 44,
    hitstun: 20,
    blockstun: 13,
    hitstop: 6,
    guardDamage: 14,
    chipDamage: 4,
    knockbackForward: 4.2,
    advance: 3.0,
    reaction: ReactionType.Knockback,
    hitbox: { reach: 2.4, radius: 1.3, height: 1.05, arc: Math.PI * 0.5 },
    cancelFrom: 8,
    cancelInto: ['v_light3'],
    energyOnHit: 24,
    shake: 0.24,
    fx: 'hit_medium',
    sfx: 'hit_medium',
  }),
  v_light3: makeAttack({
    id: 'v_light3',
    name: 'Dominion Hammer',
    kind: AttackKind.Finisher,
    startup: 11,
    active: 4,
    recovery: 24,
    damage: 72,
    hitstun: 28,
    blockstun: 16,
    hitstop: 10,
    guardDamage: 24,
    chipDamage: 7,
    knockbackForward: 14,
    knockbackUp: 3,
    advance: 3.6,
    reaction: ReactionType.Blowaway,
    hitbox: { reach: 2.6, radius: 1.45, height: 1.1, arc: Math.PI * 0.5 },
    cancelFrom: 11,
    cancelInto: [],
    energyOnHit: 36,
    shake: 0.52,
    fx: 'hit_heavy',
    sfx: 'hit_heavy',
  }),

  // ---- Heavy: armored. Veyron walks through jabs and answers with this. ---
  v_heavy: makeAttack({
    id: 'v_heavy',
    name: 'Siege Fist',
    kind: AttackKind.Heavy,
    startup: 16,
    active: 5,
    recovery: 26,
    damage: 96,
    hitstun: 30,
    blockstun: 17,
    hitstop: 11,
    guardDamage: 30,
    chipDamage: 9,
    knockbackForward: 16,
    knockbackUp: 3.5,
    advance: 4.4,
    armor: 1,
    reaction: ReactionType.Blowaway,
    hitbox: { reach: 2.8, radius: 1.5, height: 1.1, arc: Math.PI * 0.5 },
    cancelFrom: 16,
    cancelInto: [],
    energyOnHit: 44,
    shake: 0.62,
    fx: 'hit_heavy',
    sfx: 'hit_heavy',
  }),
  v_charged: makeAttack({
    id: 'v_charged',
    name: 'Siege Fist (Charged)',
    kind: AttackKind.Heavy,
    startup: 19,
    active: 6,
    recovery: 30,
    damage: 112,
    hitstun: 34,
    blockstun: 19,
    hitstop: 13,
    guardDamage: 40,
    chipDamage: 13,
    knockbackForward: 19,
    knockbackUp: 5,
    advance: 5.0,
    armor: 2,
    reaction: ReactionType.Blowaway,
    hitbox: { reach: 3.0, radius: 1.65, height: 1.1, arc: Math.PI * 0.55 },
    energyOnHit: 52,
    shake: 0.74,
    fx: 'hit_heavy',
    sfx: 'hit_heavy',
  }),

  v_launcher: makeAttack({
    id: 'v_launcher',
    name: 'Rift Uppercut',
    kind: AttackKind.Launcher,
    startup: 13,
    active: 4,
    recovery: 24,
    damage: 60,
    hitstun: 36,
    blockstun: 16,
    hitstop: 8,
    guardDamage: 18,
    chipDamage: 5,
    knockbackForward: 1.8,
    knockbackUp: 14.5,
    advance: 2.0,
    reaction: ReactionType.Launch,
    hitbox: { reach: 2.3, radius: 1.4, height: 1.25, arc: Math.PI * 0.5 },
    energyOnHit: 30,
    shake: 0.4,
    fx: 'hit_launch',
    sfx: 'hit_launch',
  }),

  // ---- Aerial: only 2 links. Veyron is not an air fighter. ---------------
  v_air1: makeAttack({
    id: 'v_air1',
    name: 'Void Cleave',
    kind: AttackKind.AirLight,
    startup: 7,
    active: 3,
    recovery: 14,
    damage: 40,
    hitstun: 19,
    blockstun: 12,
    hitstop: 5,
    guardDamage: 10,
    knockbackForward: 2.6,
    knockbackUp: 1.8,
    advance: 2.4,
    airOk: true,
    groundOk: false,
    reaction: ReactionType.Flinch,
    hitbox: { reach: 2.2, radius: 1.3, height: 0.95, arc: Math.PI * 0.5 },
    cancelFrom: 7,
    cancelInto: ['v_air2'],
    energyOnHit: 22,
    shake: 0.2,
  }),
  v_air2: makeAttack({
    id: 'v_air2',
    name: 'Collapse Axe',
    kind: AttackKind.AirHeavy,
    startup: 10,
    active: 4,
    recovery: 20,
    damage: 66,
    hitstun: 25,
    blockstun: 14,
    hitstop: 10,
    guardDamage: 18,
    chipDamage: 5,
    knockbackForward: 3,
    knockbackUp: -19,
    advance: 2.8,
    airOk: true,
    groundOk: false,
    reaction: ReactionType.Slam,
    hitbox: { reach: 2.3, radius: 1.4, height: 0.7, arc: Math.PI * 0.55 },
    energyOnHit: 34,
    shake: 0.5,
    fx: 'hit_heavy',
    sfx: 'hit_heavy',
  }),
  v_airheavy: makeAttack({
    id: 'v_airheavy',
    name: 'Tyrant Slam',
    kind: AttackKind.AirHeavy,
    startup: 13,
    active: 5,
    recovery: 22,
    damage: 84,
    hitstun: 28,
    blockstun: 15,
    hitstop: 12,
    guardDamage: 24,
    chipDamage: 8,
    knockbackForward: 2.5,
    knockbackUp: -25,
    advance: 2.5,
    armor: 1,
    airOk: true,
    groundOk: false,
    reaction: ReactionType.Slam,
    hitbox: { reach: 2.4, radius: 1.55, height: 0.6, arc: Math.PI * 0.6 },
    energyOnHit: 40,
    shake: 0.6,
    fx: 'hit_heavy',
    sfx: 'hit_heavy',
  }),
};

export const VEYRON: CharacterData = {
  id: 'veyron',
  name: 'LORD VEYRON',
  energyName: 'VOID DOMINION',
  tagline: 'The warlord who unmade a world.',

  maxHealth: 1120,
  energyPerBar: 100,
  energyBars: 5,
  energyPassiveRegen: 4.4,
  energyChargeRate: 66,

  ascensionMax: 1000,
  ascensionGainDealt: 0.5,
  ascensionGainTaken: 0.9,
  ascensionDrain: 55,
  ascensionThreshold: 1.0,

  movement: {
    walkSpeed: 6.0,
    sprintSpeed: 10.6,
    groundAccel: 46,
    groundDecel: 78,
    turnRate: 7.4,

    jumpSpeed: 13.6,
    gravity: 37,
    maxFallSpeed: 46,
    airAccel: 24,
    airSpeed: 7.8,

    flySpeed: 13.2,
    flyVerticalSpeed: 9.8,
    flyAccel: 42,
    boostMultiplier: 1.85,
    boostEnergyPerSecond: 20,

    dashDistance: 5.2,
    dashFrames: 11,
    dashIFrames: 4,
    dashCooldown: 18,
    airDashEnergyCost: 26,
    airDashCharges: 1,

    pursuitSpeed: 50,
    pursuitEnergyCost: 35,
    pursuitRange: 38,
  },

  defense: {
    guardMax: 138,
    guardRegenRate: 17,
    guardRegenDelayFrames: 44,
    guardBreakStunFrames: 54,
    guardDamageReduction: 0.9,

    parryWindowFrames: 5,
    parryPunishFrames: 30,
    parryEnergyReward: 46,

    dodgeFrames: 24,
    dodgeIFrames: 8,
    dodgeCooldown: 24,
    dodgeDistance: 4.4,

    comboEscapeCost: 100,
    comboEscapeIFrames: 34,
    comboEscapeMinHits: 3,
  },

  visual: {
    primaryColor: VOID_BLACK,
    secondaryColor: 0x1d3a42,
    energyColor: VOID_TEAL,
    rimColor: 0x7cffe4,
    height: 2.12,
    radius: 0.58,
    build: 'heavy',
  },

  audio: { pitch: 0.82, timbre: 'dark' },

  attacks,
  lightChain: ['v_light1', 'v_light2', 'v_light3'],
  airChain: ['v_air1', 'v_air2'],
  heavyAttack: 'v_heavy',
  chargedHeavyAttack: 'v_charged',
  launcher: 'v_launcher',
  airHeavyAttack: 'v_airheavy',

  abilities: [
    // 1 — Void Spear: long, piercing, punishes anyone standing still.
    makeAbility({
      id: 'void_spear',
      name: 'Void Spear',
      kind: AbilityKind.Projectile,
      slot: 1,
      energyCost: 60,
      cooldown: 40,
      startup: 14,
      active: 2,
      recovery: 20,
      airOk: true,
      groundOk: true,
      interrupt: InterruptPolicy.Cancellable,
      shake: 0.24,
      fx: 'spear',
      sfx: 'spear',
      description: 'A lance of collapsed void that pierces anything in its line.',
      projectile: {
        count: 1,
        speed: 72,
        range: 90,
        radius: 0.7,
        damage: 74,
        chipDamage: 14,
        guardDamage: 20,
        hitstun: 22,
        blockstun: 14,
        hitstop: 7,
        knockbackForward: 11,
        knockbackUp: 1.5,
        homingStrength: 0.12,
        pierce: true,
        fx: 'spear',
        color: VOID_TEAL,
      },
    }),

    // 2 — Dominion Crush: armored advancing heavy. His pressure tool.
    makeAbility({
      id: 'dominion_crush',
      name: 'Dominion Crush',
      kind: AbilityKind.Strike,
      slot: 2,
      energyCost: 110,
      cooldown: 72,
      startup: 20,
      active: 6,
      recovery: 28,
      airOk: false,
      groundOk: true,
      armor: 2,
      interrupt: InterruptPolicy.Armored,
      shake: 0.66,
      fx: 'crush',
      sfx: 'crush',
      description: 'An armored overhead that shatters guards and ends arguments.',
      strike: {
        id: 'dominion_crush_hit',
        name: 'Dominion Crush',
        kind: AttackKind.Ability,
        damage: 124,
        hitstun: 34,
        blockstun: 22,
        hitstop: 14,
        guardDamage: 62,
        chipDamage: 18,
        knockbackForward: 9,
        knockbackUp: -14,
        advance: 7.5,
        reaction: ReactionType.Slam,
        hitbox: { reach: 2.9, radius: 1.85, height: 1.0, arc: Math.PI * 0.6 },
        energyOnHit: 30,
        shake: 0.78,
        fx: 'hit_heavy',
        sfx: 'hit_heavy',
      },
    }),

    // 3 — Rift Counter: his answer to Kairo's speed. Beats offence, loses to
    //     patience — the cleanest possible counterplay relationship.
    makeAbility({
      id: 'rift_counter',
      name: 'Rift Counter',
      kind: AbilityKind.Counter,
      slot: 3,
      energyCost: 80,
      cooldown: 96,
      startup: 4,
      active: 26,
      recovery: 22,
      counterWindow: 26,
      airOk: true,
      groundOk: true,
      interrupt: InterruptPolicy.Cancellable,
      shake: 0.4,
      fx: 'counter',
      sfx: 'counter',
      description: 'Opens a rift that swallows the next blow and returns it.',
      strike: {
        id: 'rift_counter_hit',
        name: 'Rift Counter',
        kind: AttackKind.Ability,
        damage: 118,
        hitstun: 38,
        blockstun: 20,
        hitstop: 14,
        guardDamage: 40,
        chipDamage: 14,
        knockbackForward: 17,
        knockbackUp: 7,
        reaction: ReactionType.Blowaway,
        hitbox: { reach: 0, radius: 4.0, height: 1.1, arc: Math.PI },
        energyOnHit: 20,
        shake: 0.7,
        fx: 'hit_heavy',
        sfx: 'hit_heavy',
      },
    }),

    // 4 — Black Star Detonation: area control, and his get-off-me button.
    makeAbility({
      id: 'black_star_detonation',
      name: 'Black Star Detonation',
      kind: AbilityKind.AreaBlast,
      slot: 4,
      energyCost: 140,
      cooldown: 108,
      startup: 24,
      active: 4,
      recovery: 30,
      blastRadius: 9.5,
      airOk: true,
      groundOk: true,
      armor: 1,
      interrupt: InterruptPolicy.Armored,
      shake: 0.85,
      fx: 'blackstar',
      sfx: 'blackstar',
      description: 'Collapses a dead star at his feet. Everything nearby leaves.',
      strike: {
        id: 'black_star_hit',
        name: 'Black Star Detonation',
        kind: AttackKind.Ability,
        damage: 132,
        hitstun: 34,
        blockstun: 22,
        hitstop: 14,
        guardDamage: 48,
        chipDamage: 20,
        knockbackForward: 21,
        knockbackUp: 9,
        reaction: ReactionType.Blowaway,
        hitbox: { reach: 0, radius: 9.5, height: 1.1, arc: Math.PI },
        energyOnHit: 18,
        shake: 0.9,
        fx: 'blackstar',
        sfx: 'blackstar',
      },
      projectile: { color: VOID_TEAL, fx: 'blackstar' },
    }),
  ],

  ultimate: makeAbility({
    id: 'end_of_worlds',
    name: 'End of Worlds',
    kind: AbilityKind.Ultimate,
    slot: 0,
    energyCost: 400,
    cooldown: 240,
    cinematicFrames: 186,
    captureRange: 17,
    airOk: true,
    groundOk: true,
    interrupt: InterruptPolicy.Uninterruptible,
    shake: 1,
    fx: 'end_of_worlds',
    sfx: 'end_of_worlds',
    description:
      'Veyron reopens the wound he carved into Veyra and drags his enemy into it.',
    projectile: {
      count: 1,
      speed: 34,
      range: 26,
      radius: 1.3,
      damage: 22,
      chipDamage: 4,
      guardDamage: 5,
      hitstun: 9,
      blockstun: 6,
      hitstop: 2,
      knockbackForward: 1,
      knockbackUp: 0.4,
      homingStrength: 0.9,
      fx: 'end_of_worlds',
      color: VOID_TEAL,
    },
    strike: {
      id: 'end_of_worlds_hit',
      name: 'End of Worlds',
      kind: AttackKind.Ultimate,
      damage: 366,
      hitstun: 66,
      blockstun: 34,
      hitstop: 22,
      guardDamage: 120,
      chipDamage: 70,
      knockbackForward: 26,
      knockbackUp: 9,
      reaction: ReactionType.Blowaway,
      hitbox: { reach: 0, radius: 7, height: 1.2, arc: Math.PI },
      energyOnHit: 0,
      shake: 1,
      fx: 'end_of_worlds',
      sfx: 'end_of_worlds',
    },
  }),

  transformation: {
    id: 'tyrant_unbound',
    name: 'TYRANT UNBOUND',
    frames: 62,
    damageMultiplier: 1.28,
    defenseMultiplier: 0.74,
    speedMultiplier: 1.14,
    attackSpeedMultiplier: 0.9,
    energyRegenMultiplier: 2.0,
    bonusArmor: 1,
    auraColor: 0x9dfff0,
    accentColor: 0xe8fffb,
    audioProfile: 'unbound',
    cameraFovBoost: 4,
    fx: 'transform_unbound',
    sfx: 'transform_unbound',
  },
};
